first_application/urls.py
from django.urls import path
from.import views

urlpatterns = [
    #path('view',views.app),
    path('', views.app_new, name='index'),
    path('home', views.home, name= "home"),
    path('about', views.about, name= "about"),
    path('contact',views.contact, name="contact"),
    path('form', views.form, name="form"),
    path('list1', views.list1, name="list1"),
    path('edit/<pk>', views.edit_item, name='edit'),           #PK it creates id
    path('delete/<pk>', views.delete_item, name='delete'),
    
]

test_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('first_application.urls')),
    path('', include('userapp.urls')),

]

userapp/urls.py
from django.urls import path
from.import views

urlpatterns = [
    path('login',views.login_data, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.logout_data, name='logout'),
]

first_application/models.py
from django.db import models

# Create your models here.
class Form(models.Model):
    name = models.CharField(max_length = 20)
    address = models.CharField(max_length = 20)
    contact = models.CharField(max_length = 10)
    email = models.EmailField(max_length = 20, null = True)
    is_delete = models.BooleanField(default=False)

    class Meta:
        db_table = "Form"

    def __str__(self):    #helps to defined in the admin panel to search 
        return self.name

userapp/models.py
from django.db import models

# Create your models here.

first_application/views.py
import json

from django.shortcuts import render, redirect
from . models import Form
from django.contrib import messages
from django.http import JsonResponse

from . import validation

# Create your views here.

#def app(request):
    #return HttpResponse('my name is sana')

def app_new(request):
    data = {'name':'kajal','address':'lalitpur'}
    return render(request,'first_application/index.html', {'data':data}) #if there is no keyword then it will show error
    
def index(request):
    if request.user.is_authenticated:
        return render(request,'first_application/index.html')
    else:
        return redirect("/login")
    
def home(request):
    if request.user.is_authenticated:
        return render(request,'first_application/home.html')
    else:
        return redirect("/login")

def about(request):
    if request.user.is_authenticated:
        return render(request,'first_application/about.html')
    else:
        return redirect("/login")

def contact(request):
    if request.user.is_authenticated:
        return render(request, 'first_application/contact.html')
    else:
        return redirect("/login")

def form(request):
    if request.user.is_authenticated:
        try:
            if request.method == "POST":        #shows error none in method using get 
                error_list, name, address, contact, email = validation.form_edit_create(request, None)
                if error_list:
                        return JsonResponse({"error":error_list}, status=400) 
                
                Form.objects.create(name = name, address= address, contact = contact, email = email)
                return JsonResponse({"response":"ok"},status=200)
        except Exception as exe:
            print(exe)
        return render (request, 'first_application/form.html')
    else:
        return redirect("/login")

def list1(request):
    if request.user.is_authenticated:
        data = Form.objects.filter(is_delete=False)           
        return render (request, 'first_application/list1.html',{'datas':data})
    else:
        return redirect("/login")

def edit_item(request, pk):
    if request.user.is_authenticated:
        tableform = Form.objects.get(id = pk, is_delete=False)
        if request.method == "POST":
            try:
                error_list, name, address, contact, email = validation.form_edit_create(request, pk)
                if error_list:
                        return JsonResponse({"error":error_list}, status=400)
                
                Form.objects.filter(id = pk, is_delete=False).update(name = name, address= address, contact =contact,   email = email)
                return JsonResponse({"response":"ok"},status=200)
            except Exception as exe:
                print(exe)
        return render (request, 'first_application/edit.html', {'tableform':tableform})   

def delete_item(request, pk):
    data = Form.objects.get(id=pk)
    data.is_delete=True
    data.save()
    messages.success(request, 'Data delete Successfully.')
    return redirect("/list1")

userapp/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate


# Create your views here.
def base(request):
    return render(request,'userapp/index.html')

def login_data(request):
    if request.method =="POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        print(username, password)
        user = authenticate(username=username,password=password)
        if user:
            login(request, user)
            request.session['test'] = 'testing user session'
        return redirect('/home')
    else:
        logout(request)
        redirect('/login')
    return render(request,'userapp/login.html')


def register(request):
    if request.method == "POST":
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        User.objects.create_user(
            username=username,
            email=email,
            password=password
            )
        return redirect('/register')
    return render(request,'userapp/register.html')


def logout_data(request):
    logout(request)
    return redirect('/login')

first_application/templates/first_application/about.html
{% extends 'first_application/index.html' %}

{% block content %}
<h1>this is about page</h1>
{% endblock content %}

first_application/templates/first_application/contact.html
{% extends 'first_application/index.html' %}

{% block content %}
<h1>this is about contacts</h1>
{% endblock content %}

first_application/templates/first_application/edit.html
{% extends 'first_application/index.html' %}

{% block content %}

<form id="StudentEdit">
    {% csrf_token %} <!--it creates hidden value -->
    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                <label> Name </label>
                <input type="text" id="name" class="form-control" value="{{tableform.name}}" >
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label> Address </label>
                <input type="text" id="address" class="form-control" value="{{tableform.address}}" >
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label> Contact </label>
                <input type="number" id="contact" class="form-control" maxlength="10" value="{{tableform.contact}}"
                    required> <!-- name type should be matched with views -->
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label> email </label>
                <input type="email" id="email" class="form-control" value="{{tableform.email}}" >
                <!-- name type should be matched with views -->
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label> Edit </label>
                <input type="button" id="editBtn" value="Edit" class="form-control btn btn-info" >
            </div>
        </div>
    </div>
</form>
{% endblock content %}


{% block js %}
<script>
    $("#editBtn").off('click').on('click', function () {
        // to get data
        var data = {
            "username": $("#name").val(),                              <!--you have to mention id -->
            "address": $("#address").val(),
            "contact": $("#contact").val(),
            "email": $("#email").val()
        }
        //to pass data into views by using ajax
        var token = $("#StudentEdit").find("input[name=csrfmiddlewaretoken]").val();
        var id = "{{tableform.id}}"
        $.ajax({
            method: "POST",                   //which data 
            url: `/edit/${id}`,            //where to send the data
            headers: { "X-CSRFToken": token },
            data: JSON.stringify(data),            //what to send
            contentType: "application/json",
            dataType: "json",                             //convertor jason 

            success: function (response) {
                toastr.success("Data  edit successfully saved.")
                window.setTimeout(function () {
                    window.location = "/list1";
                }, 1000);
            },
            error: function (response) {
            data = response.responseJSON;
            if (data === undefined) {
                toastr.error("Internal server error.")
            }
            else {
                if (data.hasOwnProperty('error')) {
                    var li = ''
                    for (let i = 0; i < data['error'].length; i++) {
                        li += '<li>' + data['error'][i] + '</li>'
                    }
                    toastr.error(li)
                }
                else {
                    li = '<li>' + data['resultDescription'] + '</li>'
                    toastr.error(li)
                }
            }
        },
        });
    })
</script>
{% endblock js %}

first_application/templates/first_application/form.html
{% extends 'first_application/index.html' %}

{% block content %}
<form id="StudentForm">
    {% csrf_token %} <!--it creates hidden value -->
    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                <label> Name </label>
                <input type="text" id="name" class="form-control" >
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label> Address </label>
                <input type="text" id="address" class="form-control" >
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label> Contact </label>
                <input type="number" id="contact" class="form-control" maxlength="10" >
                <!-- name type should be matched with views -->
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label> email </label>
                <input type="email" id="email" class="form-control" required >
                <!-- name type should be matched with views -->
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label> Submit </label>
                <input type="button" id="submitBtn" class="form-control" value="submit">
            </div>
        </div>
    </div>
</form>
{% endblock content %}

{% block js %}
<script>
    $("#submitBtn").off('click').on('click', function () {
        // to get data
        var data = {
            "username": $("#name").val(),                              <!--you have to mention id -->
            "address": $("#address").val(),
            "contact": $("#contact").val(),
            "email": $("#email").val()
        }
        //to pass data into views by using ajax
        var token = $("#StudentForm").find("input[name=csrfmiddlewaretoken]").val();
        $.ajax({
            method: "POST",                   //which data 
            url: "/form",            //where to send the data
            headers: { "X-CSRFToken": token },
            data: JSON.stringify(data),            //what to send
            contentType: "application/json",
            dataType: "json",                             //convertor jason 

            success: function (response) {
                toastr.success("Data successfully saved.")
                window.setTimeout(function () {
                    window.location = "/form";
                }, 1000);
            },
            error: function (response) {
            data = response.responseJSON;
            if (data === undefined) {
                toastr.error("Internal server error.")
            }
            else {
                if (data.hasOwnProperty('error')) {
                    var li = ''
                    for (let i = 0; i < data['error'].length; i++) {
                        li += '<li>' + data['error'][i] + '</li>'
                    }
                    toastr.error(li)
                }
                else {
                    li = '<li>' + data['resultDescription'] + '</li>'
                    toastr.error(li)
                }
            }
        },
        });
    })
</script>
{% endblock js %}

first_application/templates/first_application/home.html
{% extends 'first_application/index.html' %}

{% block content %}
<h1>this is home page</h1>
{% endblock content %}

first_application/templates/first_application/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Online shopping system</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Fonts -->
    <link href="{% static 'first_application/css/plugin/google.font.family.min.css' %}" rel="stylesheet">
    <!-- CSS Libraries -->
    <link href="{% static 'first_application/css/plugin/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'first_application/css/fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'first_application/css/plugin/toaster.css' %}">
    <link rel="stylesheet" href="{% static 'first_application/css/plugin/adminlte.min.css' %}" />

    <link rel="stylesheet" href="//cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.4.2/css/buttons.dataTables.min.css">



    {% block css %}
    {% endblock css %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'index' %}">My Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only"></span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'about' %}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'contact' %}">Contact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'form' %}">Form</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'list1' %}">List</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
            </ul>
        </div>
    </nav>
    {% block content %}


    {% endblock content %}


    <!-- JavaScript Libraries -->
    <!-- jQuery -->

    <!-- Template Javascript -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <script src="{% static 'first_application/js/plugin/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'first_application/js/plugin/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'first_application/js/plugin/toaster.min.js' %}"></script>

    <script src="{% static 'first_application/js/plugin/adminlte.min.js' %}"></script>
    <script src="//cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/2.4.2/js/dataTables.buttons.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.print.min.js"></script>
    <!-- <script src="{% static 'js/plugin/demo1.js' %}"></script> -->

    <!-- <script src="{% static 'js/plugin/base.min.js' %}"></script> -->
    {% block js %}
    {% endblock js %}
</body>

</html>

first_application/templates/first_application/list1.html
{% extends 'first_application/index.html' %}
{% load static %}

{% block content %}

<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover" id="mytable">
        <thead>
            <tr>
                <th scope="col">S.N</th>
                <th scope="col">Name</th>
                <th scope="col">Address</th>
                <th scope="col">Contact</th>
                <th scope="col">Email</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for data in datas %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{data.name}}</td>
                <td>{{data.address}}</td>
                <td>{{data.contact}}</td>
                <td>{{data.email}}</td>
                <td>
                    {% if perms.first_application.change_form %}
                    <a href="{% url 'edit' data.id %}" class="btn btn-info btn-sm">Edit</a>
                    {% endif %}

                    {% if perms.first_appliction.delete_form %}
                    <form class="d-inline" method="POST" action="{% url 'delete' data.id %}">
                        {% csrf_token %}
                        <input type="submit" class="btn btn-danger btn-sm" value="Delete">
                    </form>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

{% block js %}
<script>
    $(document).ready(function() {
        $('#mytable').DataTable({
            dom: 'Bfrtip',
            buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print'
            ]
        });
    });
</script>
{% endblock js %}

first_application/templates/first_application/try.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Online shopping system</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Fonts -->
    <link href="{% static 'first_application/static/css/plugin/google.font.family.min.css' %}" rel="stylesheet">
    <!-- CSS Libraries -->
    <link href="{% static 'first_application/static/css/plugin/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'first_application/static/css/fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'first_application/static/css/plugin/adminlte.min.css' %}" />

    {% block css %}
    {% endblock css %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'index' %}">My Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only"></span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'about' %}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'contact' %}">Contact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'form' %}">Form</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'list1' %}">List</a>
                </li>
            </ul>
        </div>
    </nav>
    {% block content %}


    {% endblock content %}


    <!-- JavaScript Libraries -->
    <!-- jQuery -->

    <!-- Template Javascript -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <script src="{% static 'first_application/static/js/plugin/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'first_application/static/js/plugin/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'first_application/static/js/plugin/adminlte.min.js' %}"></script>
    <!-- <script src="{% static 'js/plugin/demo1.js' %}"></script> -->

    <!-- <script src="{% static 'js/plugin/base.min.js' %}"></script> -->
    {% block script %}
    {% endblock script %}

</body>

</html>

userapp/templates/userapp/login.html
<!DOCTYPE html>

{% load static %}

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Log in</title>
    <!-- Google Font: Source Sans Pro -->
    <link href="{% static 'first_application/css/plugin/google.font.family.min.css' %}" rel="stylesheet">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'first_application/css/fontawesome-free/css/all.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'first_application/css/plugin/icheck-bootstrap.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'first_application/css/plugin/adminlte.min.css' %}">
</head>

<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <a hef="">Online Shopping</a>
        </div>
        <div class="card">
            <div class="card-body login-card-body">
                <p class="login-box-msg">Sign in to start your session</p>
                <form id="userForm" method="POST" action="/login">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder="username" name="username" required>
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <input type="password" class="form-control" placeholder="Password" name="password" required>
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-8">
                            <div class="icheck-primary">
                                <input type="checkbox" id="remember">
                                <label for="remember">
                                    Remember Me
                                </label>
                            </div>
                        </div>
                        <div class="col-4">
                            <input type="submit" class="btn btn-primary btn-block" value="Sign In" id="loginBtn">
                        </div>
                    </div>
                </form>
                <div>
                    <p class="mb-1">
                        <a href="#" id="forgotPassword">Forgot password</a>
                    </p>
                    <p class="mb-0">
                        <a href="{% url 'register' %}" class="text-center">Register</a>
                    </p>
                </div>
            </div>
        </div>
    </div>

    <!-- REQUIRED SCRIPTS -->

    <!-- jQuery -->
    <script src="{% static 'first_application/js/plugin/jquery.min.js' %}"></script>
    <!-- jquery form validator -->
    <script src="{% static 'first_application/js/plugin/jquery.validator.min.js' %}"></script>

    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>

    <!-- toaster plugin -->
    <script src="{% static 'first_application/js/plugin/toaster.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'first_application/js/plugin/bootstrap.bundle.min.js' %}"></script>
    <!-- toaster CSS only -->
    <link rel="stylesheet" href="{% static 'jango_class/css/plugin/toaster.css' %}" />
    <!-- AdminLTE App -->
    <script src="{% static 'first_application/js/plugin/adminlto.min.js' %}"></script>
    <!--custom js file -->

</body>

</html>

userapp/templates/userapp/register.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <title>Login</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'first_application/css/plugin/bootstrap.4.6.min.css' %}" />

    <link rel="stylesheet" href="{% static 'first_pplication/css/plugin/toaster.css' %}" />
    <link rel="stylesheet" href="{% static 'first_application/css/project_css/base.css' %}" />
    <link rel="stylesheet" href="{% static 'first_application/css/project_css/user_signup.css' %}" />

</head>

<body>

    <section class="vh-100 bg-image"
        style="background-image: url('https://mdbcdn.b-cdn.net/img/Photos/new-templates/search-box/img4.webp');">
        <div class="mask d-flex align-items-center h-100 gradient-custom-3">
            <div class="container h-100">
                <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                        <div class="card" style="border-radius: 15px;">
                            <div class="card-body p-5">
                                <h2 class="text-uppercase text-center mb-5">Create an account First</h2>
                                <form id="userRegister" action="/register" method='POST'>
                                    {% csrf_token %}
                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="username">User Name:</label>
                                        <input type="text" id="username" class="form-control input-sm"
                                            name="username" />
                                    </div>

                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="email">Email:</label>
                                        <input type="email" id="email" class="form-control input-sm" name="email" />
                                    </div>


                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="password">Password</label>
                                        <input type="password" id="password" class="form-control input-sm"
                                            name="password" />
                                    </div>

                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="cPassword">password(again):</label>
                                        <input type="password" id="cPassword" class="form-control input-sm"
                                            name="cPassword" />
                                    </div>
                                    <div class="d-flex justify-content-center">
                                        <input type="submit" value="Register" id="signUpBtn"
                                            class="btn btn-success btn-block btn-lg gradient-custom-4 text-body">
                                    </div>
                                    <p class="text-center text-muted mt-5 mb-0">Have already an account? <a
                                            href="{% url 'login' %}" class="fw-bold text-body"><u>Login here</u></a></p>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
<script src="{% static 'first_application/js/plugin/jquery.min.js' %}"></script>
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>
<script src="{% static 'first_application/js/plugin/toaster.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'first_application/js/plugin/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'first_application/js/plugin/project_js/custom.js' %}"></script>

<script src="{% static 'first_application/js/plugin/project_js/user_signup.js' %}"></script>


</html>